import React, { createContext, useContext, useState, memo } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = memo(({ children }) => {
  const [language, setLanguage] = useState('en'); // 'en' or 'fr'

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'fr' : 'en');
  };

  const t = (key) => translations[language]?.[key] || key;

  const translations = {
    en: {
      // Navbar
      home: 'Home',
      about: 'About',
      services: 'Services',
      ministries: 'Ministries',
      events: 'Events',
      forms: 'Forms',
      give: 'Give',
      contact: 'Contact',
      increasingFaith: 'Increasing Faith',
      augmentFaithMinistries: 'Increasing Faith of Christ Ministries International',

      // Footer
      quickLinks: 'Quick Links',
      getInvolved: 'Get Involved',
      connect: 'Connect',
      totalNsimeyong: 'Total Nsimeyong, Yaoundé',
      phone: '+237 672 796 404',
      email: 'increasingfaithofchristm@gmail.com',
      copyright: '© 2025 Increasing Faith Of Christ Ministries International. All rights reserved.',
      motto: 'Motto: Restoration, Manifestation, Teaching Spiritual Realities',
      solo: 'Solo: Increasing Faith of Christ Ministry, All: We are an Increase.',
      raisingGeneration: 'Raising a generation passionate about the Kingdom of God.',

      // HomePage sections
      ourLeadership: 'Our Leadership',
      seniorPastorFounder: 'Senior Pastor & Founder',
      readMore: 'Read More',
      associatePastor: 'Associate Pastor',
      headOfEvangelism: 'Head of Evangelism',
      womenFellowshipLeader: "Women's Fellowship Leader",
      youthMinistryCoordinator: 'Youth Ministry Coordinator',

      // Hero
      ministriesHero: 'Ministries',
      welcomeToIFCM: 'Welcome to Increasing Faith Of Christ Ministries',
      bibleBelievingChurch: 'A Bible-believing church raising a generation passionate about the Kingdom of God. Join us for Spirit-filled worship, practical teaching, and transformative community.',
      joinUsSunday: 'Join Us Sunday',
      learnMore: 'Learn More',
      founded: 'Founded',
      members: 'Members',

      // About
      aboutUs: 'About Us',
      ourStory: 'Our Story',
      ourStoryText: 'Increasing Faith of Christ Ministries (IFCM) was founded in 2019 with a vision to raise a generation passionate about the Kingdom of God. Under the leadership of Prophet W.T. Milton, we have grown from a small gathering to a vibrant community of believers committed to discipleship, evangelism, and spiritual growth.',
      ourVision: 'Our Vision',
      ourVisionText: 'To be a beacon of hope and transformation in our community, equipping believers with the knowledge of God\'s Word and empowering them to live out their faith boldly.',
      ourMission: 'Our Mission',
      ourMissionText: 'To preach the Gospel, make disciples, and build a community where every member can grow spiritually, serve effectively, and impact the world for Christ.',

      // Services
      ourServices: 'Our Services',
      sundayWorship: 'Sunday Worship',
      sundayWorshipText: 'Join us every Sunday for powerful worship services filled with praise, prayer, and the preaching of God\'s Word.',
      bibleStudy: 'Bible Study',
      bibleStudyText: 'Deepen your understanding of Scripture through our weekly Bible study sessions and small group discussions.',
      prayerMeetings: 'Prayer Meetings',
      prayerMeetingsText: 'Experience the power of corporate prayer as we intercede for our community, nation, and the world.',
      youthMinistry: 'Youth Ministry',
      youthMinistryText: 'Empowering the next generation with faith, purpose, and leadership skills for Kingdom impact.',

      // About
      aboutProphetWTMilton: 'About Prophet WT Milton',
      showMore: 'Show More',
      showLess: 'Show Less',
      whatWeBelieveAndTeach: 'WHAT WE BELIEVE AND TEACH',
      showMoreBeliefs: 'Show More Beliefs',
      prophetWTMiltonIntro: 'Prophet WT.Milton. Through an anointed ministry spanning over 10 years, Pastor, teacher, healing minister, writer and recording Music minister and best-selling, Prophet WT. Milton has helped millions experience a victorious and purposeful life in God\'s word.',
      prophetWTMiltonBooks: 'He is the author of the best-seller My Family Must See Light, the number one family Prayer and Bible-study guide. He has also written several books worth reading like The step up series , Compulsory Training manual for workers and leaders , Essential truths for Christian believers and a host of other training manuals and tracks.',
      prophetWTMiltonMinistry: 'Prophet WT Milton pastors one of the largest congregations in Yaoundé - Cameroon. He holds massive prophetic Prayers , teaching , healing and deliverance services like Commanding the year Fasting and prayers , This mountain must be removed , My Family Must see light ,The army must drown , healing services and Prophetic healing and deliverance services with thousands in attendance globally.',
      prophetWTMiltonGifts: 'The world-renowned Prophetic, Healing and deliverance ministry of Prophet WT .Milton has helped many receive their healing and miracles through the gifts of the Spirit in operation.',
      prophetWTMiltonSchools: 'With a burning desire to bring God\'s word to all men in simplicity and with the power of the spirit, the man of God, Prophet WT Milton has established the IFC foundation school for new converts and the IFC School Of Ministry, specifically to train and equip ministers of the gospel of Christ, building in them the realities of God\'s word and empowering them to carry the message of eternal life in Christ Jesus to Power and Character.',
      prophetWTMiltonPhilanthropy: 'Prophet WT Milton is creating impact through his philanthropic works in areas of health as a trained and experienced health personnel attending to the sick and treating them of sicknesses and his yearly academic scholarship program aimed at eradicating the obstacle of financial constraints.',
      aboutIFC: 'About IFC',
      experiencePowerOfGod: 'Experience The Power of God',
      ifcDescription: 'Increasing Faith of Christ ministries International is a dynamic Pentecostal Christian Church founded by the man of God – Prophet WT Milton. It is a big family of power, glory and the unfathomable flow of God\'s blessings. God continues to increase this family, even as he continues to show his mighty works through our founder – Prophet WT Milton . We are located in Yaoundé Cameroun, where God\'s Presence and power is saving, healing and restoring human destinies and dignities!',
      ifcFoundation: 'Upon God\'s divine instruction, Prophet WT Milton got the directive to start this ministry and also the name to give it. He named the ministry "Increasing Faith of Christ" in total obedience to the word of God. Increasing Faith of Christ ministries was founded on the 28th of April with 29 members and has since then grown to higher heights.',

      // Services
      serviceTimes: 'Service Times',
      joinUsWorshipFellowship: 'Join us for worship and fellowship',
      sundayService: 'Sunday Service',
      sundayServiceDesc: 'Experience powerful worship, prophetic teaching, and the presence of God',
      firstService: 'First Service: 8:00 AM - 10:30 AM',
      location: 'Location: Total Nsimeyong, Yaoundé',
      midweekService: 'Midweek Service',
      midweekServiceDesc: 'Join us for Bible study, intercession, and deeper fellowship',
      midweekServiceTime: 'Service: Wednesday - 6:00 PM',
      focus: 'Focus: Teaching & Prayer',
      headquarters: 'Headquarters: Total Nsimeyong, Yaoundé, Cameroon',
      everyoneWelcome: 'Everyone is welcome! Come as you are.',

      // Ministries
      ourMinistries: 'Our Ministries',
      findYourPlace: 'Find your place to serve and grow',
      joinAMinistry: 'Join a Ministry',
      worshipTeamName: 'Worship Team (Levites)',
      worshipTeamDesc: 'Ushering in the presence of God through prophetic music and Spirit-led worship',
      youthForImpactName: 'Youth for Impact',
      youthForImpactDesc: 'Empowering the next generation through mentorship, service, and revival',
      mothersOfNationsName: 'Mothers of Nations',
      mothersOfNationsDesc: 'A support and prayer network for women walking in their God-given purpose',
      intercessionArmyName: 'Intercession Army',
      intercessionArmyDesc: 'Warriors standing in the gap for the church and the nations',
      evangelismSquadName: 'Evangelism Squad',
      evangelismSquadDesc: 'Taking the gospel to streets, hospitals, prisons, and remote communities',
      childrenMinistryName: "Children's Ministry",
      childrenMinistryDesc: 'Nurturing young hearts to know and love Jesus from an early age',

      // Forms
      formsAndRegistration: 'Forms & Registration',
      connectThroughForms: 'Connect with us through these forms',
      shareYourTestimony: 'Share Your Testimony',
      newConvertForm: 'New Convert Form',
      membershipForm: 'Membership Form',
      registerForIFCMEducationalProgram: 'Register for IFCM Educational Program',
      counselingAppointment: 'Counseling Appointment',
      joinAServiceGroup: 'Join a Service Group',
      preMaritalCounseling: 'Pre-Marital Counseling',
      postMaritalCounseling: 'Post-Marital Counseling',
      childDedication: 'Child Dedication',
      invitedGuestForm: 'Invited Guest Form',
      myAnsweredPrayerSlip: 'My Answered Prayer Slip',

      // Form placeholders
      fullName: 'Full Name *',
      emailAddress: 'Email Address *',
      phoneNumber: 'Phone Number',
      yourTestimony: 'Your Testimony *',
      dateOfTestimony: 'Date of Testimony',
      dateOfConversion: 'Date of Conversion *',
      howDidYouHear: 'How did you hear about IFCM?',
      prayerRequests: 'Prayer Requests',
      address: 'Address *',
      dateOfBirth: 'Date of Birth *',
      maritalStatus: 'Marital Status',
      occupation: 'Occupation',
      emergencyContactName: 'Emergency Contact Name',
      emergencyContactPhone: 'Emergency Contact Phone',
      programOfInterest: 'Program of Interest *',
      previousMinistryExperience: 'Previous Ministry Experience',
      whatDoYouHopeToGain: 'What do you hope to gain?',
      preferredDate: 'Preferred Date *',
      preferredTime: 'Preferred Time',
      typeOfCounseling: 'Type of Counseling',
      briefDescriptionOfIssue: 'Brief description of the issue *',
      serviceGroup: 'Service Group *',
      relevantExperienceOrSkills: 'Relevant Experience or Skills',
      availability: 'Availability (days/times)',
      partner1FullName: 'Partner 1 Full Name *',
      partner1Email: 'Partner 1 Email *',
      partner1Phone: 'Partner 1 Phone *',
      partner2FullName: 'Partner 2 Full Name *',
      partner2Email: 'Partner 2 Email *',
      partner2Phone: 'Partner 2 Phone *',
      expectedWeddingDate: 'Expected Wedding Date',
      howLongHaveYouBeenDating: 'How long have you been dating?',
      anySpecificConcerns: 'Any specific concerns or topics to discuss?',
      spouseName: 'Spouse Name',
      yearsMarried: 'Years Married',
      issuesToAddress: 'Issues you would like to address *',
      parent1FullName: 'Parent 1 Full Name *',
      parent1Email: 'Parent 1 Email *',
      parent1Phone: 'Parent 1 Phone *',
      parent2FullName: 'Parent 2 Full Name',
      parent2Email: 'Parent 2 Email',
      parent2Phone: 'Parent 2 Phone',
      childFullName: 'Child Full Name *',
      childDateOfBirth: 'Child Date of Birth *',
      eventServiceAttending: 'Event/Service Attending *',
      numberOfGuests: 'Number of Guests (including yourself)',
      specialNeeds: 'Special Needs or Accommodations',
      originalPrayerRequest: 'Original Prayer Request *',
      howGodAnswered: 'How God Answered *',
      dateAnswered: 'Date Answered',
      additionalInformation: 'Additional Information',
      submitForm: 'Submit Form',

      // Leadership
      prophetName: 'Prophet W.T. Milton',
      prophetDescription: 'Prophet W.T. Milton is a seasoned servant of God with a prophetic mantle and a deep passion for discipleship. Called into ministry through a divine encounter, he has dedicated his life to raising end-time warriors who are rooted in Christ. Under his leadership, IFCM has grown both spiritually and numerically, impacting lives across Cameroon and beyond.',
      leader1Name: 'Pastor Anna N.',
      leader2Name: 'Evangelist Samuel T.',
      leader3Name: 'Sister Martha L.',
      leader4Name: 'Brother Joel M.',

      // Events
      upcomingEvents: 'Upcoming Events',
      joinUsForLifeChangingExperiences: 'Join us for life-changing experiences',

      // Give
      partnerWithUs: 'Partner With Us',
      supportTheKingdomWork: 'Support the Kingdom work through your giving',
      mobileMoney: 'Mobile Money',
      mtnMoMo: 'MTN MoMo',
      ifcProjects: 'IFC Projects',
      orangeMoney: 'Orange Money',
      tithesOfferings: 'Tithes & Offerings',
      waysToGive: 'Ways to Give',
      tithesOfferingsDesc: 'Support regular church operations',
      kingdomCenterProject: 'Kingdom Center Project',
      buildOurPermanentWorshipCenter: 'Build our permanent worship center',
      mercyHandsProject: 'Mercy Hands Project',
      supportHumanitarianOutreach: 'Support humanitarian outreach',
      missionsEvangelism: 'Missions & Evangelism',
      reachTheUnreached: 'Reach the unreached with the gospel',
      giveQuote: '"Give, and it will be given to you. A good measure, pressed down, shaken together and running over." - Luke 6:38',

      // Contact
      contactUs: 'Contact Us',
      wedLoveToHearFromYou: "We'd love to hear from you",
      locationLabel: 'Location',
      phoneLabel: 'Phone',
      emailLabel: 'Email',
      followUs: 'Follow Us',
      sendUsAMessage: 'Send Us a Message',
      yourName: 'Your Name *',
      yourEmail: 'Your Email *',
      yourPhone: 'Your Phone',
      yourMessage: 'Your Message *',
      sendMessage: 'Send Message',

      // Beliefs
      belief1Title: 'Love one another:',
      belief1Content: '(Matthew 5:43-44) Jesus said the only way the world would know you are my disciples is when you obey my commandment which is, loving one another (John 13:34-35). The greatest form of Spirituality is manifested through LOVE. (1John 2:9, 12, Rom 13:8, 1John 4:7-8, 16, 20-21)',
      belief2Title: 'The Holy Bible:',
      belief2Content: 'At Increasing Faith of Christ Ministry, We believe the word of God is our gospel truth and all we need for our dying world because it is God\'s power unto salvation. (Romans 1:16, Matthew 4; 4, Acts 6:4, Matt 8:8)',
      belief3Title: 'The Use Of The Name Of Jesus',
      belief3Content: 'At I.F.C.M, We make all requests and petitions in Jesus\' name (Phil 2:9-11, John 14; 13-14, 1John 3:22-23).',
      belief4Title: 'The Godhead (Trinity):',
      belief4Content: 'This speaks of the union of God the Father, the Son and the Holy Ghost. (Col 2:9). They bear witness in heaven (united) (1John 5:7, Matt 28:19, Genesis 1:26-27, John 1:14, Acts 3: 4)',
      belief5Title: 'Water Baptism:',
      belief5Content: 'The word baptism comes from a Greek word \'baptizo\' which means to: Immerse, Submerse or bury. The immersion i.e (deepening believers in water) shows their death, burial and resurrection with Christ Jesus. In order words, baptism is a sacrament commanded to us by Christ Jesus which signifies our death and resurrection with Him through our faith in the active power of God which raised Christ from death. (Col 2;13, Matt 29:19, Mark 16:13-16, Mark 1:9).',
      belief6Title: 'Holy Ghost Baptism:',
      belief6Content: 'The baptism of the Holy Ghost is the empowerment by the Holy Spirit for a sign and for us to bear witness (Acts 1:4-5, 8, mark 1:8). The ability to speak in tongues follows (Acts 2:4, 1 Cor 14:2, 4, 14)',
      belief7Title: 'Power and Authority:',
      belief7Content: 'We believe that all Authority is in the Jesus\' and He has given us this authority to provide solutions to people\'s problems in His name.',
      belief8Title: 'The importance of the Cross:',
      belief8Content: 'How that Jesus died and rose, and his blood paid the price for our us salvation. We know that by his strips we were healed',
      belief9Title: 'Repentance:',
      belief9Content: 'Repentance means turning from your evil ways, conversion of those who are in the world and also those who were once in faith and have backslided (Matt 4:16-17, Acts 2:38) Acts 3:19 says \'Repent and be converted\'. To be born again is to obey (Rom 10:9-10), to be born of God (John 1:13, 1Peter 1:23).',
      belief10Title: 'Fasting And Prayers:',
      belief10Content: 'Christians are bound to fast and pray, which is the one of the sure means whereby we draw near to God (Matt 9:15). We receive from God through prayers (Mark 11:24, Luke 2:37, James 5:16, Matt 4:2, Matt 17: 21).',
      belief11Title: 'Miracles And Healings, (Gifts From God, Laying Of Hands):',
      belief11Content: 'God works in diverse ways, the miracles we see are by the power of God. Imagine a lame walking, the blind seeing etc it is given by God (1 Cor 12:10, Acts 15:12, Gal 5:3). Healing is of God not man (1Corin 12:9) Jesus himself gave the pronouncement in Mark 16:18 \'They shall take up serpents and if they drink any deadly water, it shall not harm them, they shall lay hands on the sick and they shall recover\'. James 5:14-16, Mark 6:13, 1 Timothy 5:22, also talks of anointing with olive oil for healing.',
      belief12Title: 'Discipleship:',
      belief12Content: 'The act of making Christianity to continue is to follow. There must be a master (Luke 14:26-27) Jesus is the unseen master but he puts a master in place who we can see (overseer of the ministry), (Mat 9:14). Apostle Paul was a master in 1Corin 4:15 and 1 Cor 11:1 he said \'follow me as I follow Christ\'.',
      belief13Title: 'Submission To Church Authority.',
      belief13Content: 'The loyalty of every member should be paramount. There should never be any room for gang up (fractions to resist authority), (Heb 13:17, Mat 10:24), (see Essential Truth for Beginners in Christian Faith and read on Loyalty by W.T Milton).',
      belief14Title: 'Forgiveness and Reconciliation',
      belief14Content: 'The constitution part of justification is forgiveness, which is to pardon or to be pardoned. God absorbed us of our sins, which is one of the conditions of becoming part of God\'s kingdom. The Lord\'s Prayer explains it in Matt 6:12, 15, you must forgive others so that God forgives you and if you do not forgive, God will not forgive you. See what Christ said in Matt 18:21-22.',
      belief15Title: 'Holy Communion (The Lord\'s Supper).',
      belief15Content: 'Jesus and his disciples broke bread and ate, He poured wine and they drank, Jesus said, the bread is His body and the wine is His blood (1Cor 11:20, 10:16). It is a blessing from the Lord that we do in commemoration of Jesus (Matt 26:26-29, Mark 14:22-25, Luke 22:19-20). It is the only thing Christ said we should do in remembrance of Him.',
      belief16Title: 'Holy Matrimony',
      belief16Content: 'Every man must be a husband to a wife (Gen 2:24-25, Titus 1:6). Divorce is not permitted except on the condition of adultery. (Matt 5:31-32). If you leave your spouse stay unmarried (Matt 19:9-12, 1Cor 7:10-11). No believer is allowed to marry an unbeliever (2Cor 6:14-18).',
      belief17Title: 'Integrity',
      belief17Content: 'Integrity is our stand and watch word (Prov 20:7). It brings about a better world. If all families have integrity, their children will take after them and that will bring about a better community, neighborhood, home, town, state, and world.',

      // Events
      event1Title: 'This Mountain Must Be Removed',
      event1Date: 'August 2025',
      event1Description: 'A powerful crusade focused on breaking barriers and moving spiritual mountains',
      event2Title: 'My Family Must See Light',
      event2Date: 'November 2025',
      event2Description: 'Family transformation and breakthrough conference',
      event3Title: 'Healing & Deliverance Crusade (Cross Over)',
      event3Date: 'December 2025',
      event3Description: 'Year-end healing service and crossover night celebration',
      event4Title: "Kingdom Women's Conference",
      event4Date: 'April 2026',
      event4Description: 'Empowering women to walk in their kingdom authority',

      // Add more as needed
    },
     fr: {
       // Navbar
       home: 'Accueil',
       about: 'À propos',
       services: 'Services',
       ministriesHero: 'Ministères',
       events: 'Événements',
       forms: 'Formulaires',
       give: 'Donner',
       contact: 'Contact',
       increasingFaith: 'Augmenter la Foi',
       augmentFaithMinistries: 'Augmenter la foi des Ministères du Christ International',

       // Footer
       quickLinks: 'Liens Rapides',
       getInvolved: 'S\'impliquer',
       connect: 'Se Connecter',
       totalNsimeyong: 'Total Nsimeyong, Yaoundé',
      phone: '+237 672 796 404',
      email: 'increasingfaithofchristm@gmail.com',
      copyright: '© 2025 Ministère International de l\'Augmentation de la Foi du Christ. Tous droits réservés.',
       motto: 'Devise: Restauration, Manifestation, Enseignement des Réalités Spirituelles',
       solo: 'Solo: Ministère de l\'Augmentation de la Foi du Christ, Tous: Nous sommes une Augmentation.',
       raisingGeneration: 'Élever une génération passionnée par le Royaume de Dieu.',

       // HomePage sections
       ourLeadership: 'Notre Leadership',
       seniorPastorFounder: 'Pasteur Principal & Fondateur',
       readMore: 'En Savoir Plus',
       associatePastor: 'Pasteur Associé',
       headOfEvangelism: 'Chef de l\'Évangélisation',
       womenFellowshipLeader: 'Leader de la Fraternité des Femmes',
       youthMinistryCoordinator: 'Coordinateur du Ministère des Jeunes',

       // Hero
       welcomeToIFCM: 'Bienvenue au Ministère de l\'Augmentation de la Foi du Christ',
       bibleBelievingChurch: 'Une église croyant à la Bible, élevant une génération passionnée par le Royaume de Dieu. Rejoignez-nous pour un culte rempli de l\'Esprit, un enseignement pratique et une communauté transformative.',
       joinUsSunday: 'Rejoignez-nous Dimanche',
       learnMore: 'En Savoir Plus',
       founded: 'Fondé',
       members: 'Membres',

       // About
       aboutUs: 'À propos de nous',
       ourStory: 'Notre Histoire',
       ourStoryText: 'L\'Augmentation de la Foi du Christ (IFCM) a été fondée en 2019 avec la vision d\'élever une génération passionnée par le Royaume de Dieu. Sous la direction du Prophète W.T. Milton, nous sommes passés d\'un petit groupe à une communauté dynamique de croyants engagés dans le discipulat, l\'évangélisation et la croissance spirituelle.',
       ourVision: 'Notre Vision',
       ourVisionText: 'Être un phare d\'espoir et de transformation dans notre communauté, équipant les croyants avec la connaissance de la Parole de Dieu et les encourageant à vivre leur foi avec audace.',
       ourMission: 'Notre Mission',
       ourMissionText: 'Prêcher l\'Évangile, faire des disciples et bâtir une communauté où chaque membre peut grandir spirituellement, servir efficacement et impacter le monde pour Christ.',

      // Services
      ourServices: 'Nos Services',
      sundayWorship: 'Culte du Dimanche',
      sundayWorshipText: 'Rejoignez-nous chaque dimanche pour des cultes puissants remplis de louange, de prière et de la prédication de la Parole de Dieu.',
      bibleStudy: 'Étude Biblique',
      bibleStudyText: 'Approfondissez votre compréhension des Écritures grâce à nos sessions hebdomadaires d\'étude biblique et de discussions en petits groupes.',
      prayerMeetings: 'Réunions de Prière',
      prayerMeetingsText: 'Vivez la puissance de la prière collective alors que nous intercédons pour notre communauté, notre nation et le monde.',
      youthMinistry: 'Ministère des Jeunes',
      youthMinistryText: 'Donner du pouvoir à la prochaine génération avec la foi, le but et les compétences de leadership pour un impact dans le Royaume.',

      // About
      aboutProphetWTMilton: 'À propos du Prophète WT Milton',
      showMore: 'Voir Plus',
      showLess: 'Voir Moins',
      whatWeBelieveAndTeach: 'CE QUE NOUS CROYONS ET ENSEIGNONS',
      showMoreBeliefs: 'Voir Plus de Croyances',
      prophetWTMiltonIntro: 'Le Prophète WT.Milton. Grâce à un ministère oint s\'étendant sur plus de 10 ans, Pasteur, enseignant, ministre de guérison, écrivain et ministre de musique d\'enregistrement et best-seller, le Prophète WT. Milton a aidé des millions de personnes à expérimenter une vie victorieuse et pleine de sens dans la Parole de Dieu.',
      prophetWTMiltonBooks: 'Il est l\'auteur du best-seller Ma Famille Doit Voir la Lumière, le guide numéro un de prière et d\'étude biblique familiale. Il a également écrit plusieurs livres à lire comme la série The step up, Manuel de formation obligatoire pour les travailleurs et les leaders, Vérités essentielles pour les croyants chrétiens et une multitude d\'autres manuels et pistes de formation.',
      prophetWTMiltonMinistry: 'Le Prophète WT Milton pastoure l\'une des plus grandes congrégations de Yaoundé - Cameroun. Il organise des prières prophétiques massives, des enseignements, des services de guérison et de délivrance comme Commander l\'année Jeûne et prières, Cette montagne doit être enlevée, Ma Famille Doit voir la lumière, L\'armée doit se noyer, services de guérison et services prophétiques de guérison et de délivrance avec des milliers de participants à l\'échelle mondiale.',
      prophetWTMiltonGifts: 'Le ministère prophétique, de guérison et de délivrance de renommée mondiale du Prophète WT .Milton a aidé beaucoup de gens à recevoir leur guérison et leurs miracles grâce aux dons de l\'Esprit en opération.',
      prophetWTMiltonSchools: 'Avec un ardent désir d\'apporter la Parole de Dieu à tous les hommes en simplicité et avec la puissance de l\'esprit, l\'homme de Dieu, le Prophète WT Milton a établi l\'école de fondation IFC pour les nouveaux convertis et l\'École IFC du Ministère, spécifiquement pour former et équiper les ministres de l\'Évangile du Christ, en construisant en eux les réalités de la Parole de Dieu et en les habilitant à porter le message de la vie éternelle en Christ Jésus avec Puissance et Caractère.',
      prophetWTMiltonPhilanthropy: 'Le Prophète WT Milton crée un impact grâce à ses œuvres philanthropiques dans les domaines de la santé en tant que personnel de santé formé et expérimenté soignant les malades et les traitant de maladies et son programme annuel de bourses académiques visant à éliminer l\'obstacle des contraintes financières.',
      aboutIFC: 'À propos d\'IFC',
      experiencePowerOfGod: 'Expérimentez la Puissance de Dieu',
      ifcDescription: 'L\'Augmentation de la Foi du Christ ministères International est une église chrétienne pentecôtiste dynamique fondée par l\'homme de Dieu – Prophète WT Milton. C\'est une grande famille de puissance, de gloire et des bénédictions insondables de Dieu. Dieu continue d\'augmenter cette famille, tout en montrant ses œuvres puissantes à travers notre fondateur – Prophète WT Milton. Nous sommes situés à Yaoundé Cameroun, où la Présence et la puissance de Dieu sauvent, guérissent et restaurent les destins et les dignités humaines!',
      ifcFoundation: 'Sur l\'instruction divine de Dieu, le Prophète WT Milton a reçu la directive de commencer ce ministère et aussi le nom à lui donner. Il a nommé le ministère "Augmentation de la Foi du Christ" en totale obéissance à la Parole de Dieu. L\'Augmentation de la Foi du Christ ministères a été fondée le 28 avril avec 29 membres et a depuis grandi à des hauteurs plus élevées.',

      // Services
      serviceTimes: 'Heures de Service',
      joinUsWorshipFellowship: 'Rejoignez-nous pour le culte et la communion',
      sundayService: 'Service du Dimanche',
      sundayServiceDesc: 'Expérimentez un culte puissant, un enseignement prophétique et la présence de Dieu',
      firstService: 'Premier Service: 8:00 AM - 10:30 AM',
      location: 'Lieu: Total Nsimeyong, Yaoundé',
      midweekService: 'Service de Mi-Semaine',
      midweekServiceDesc: 'Rejoignez-nous pour l\'étude biblique, l\'intercession et une communion plus profonde',
      midweekServiceTime: 'Service: Mercredi - 18:00',
      focus: 'Focus: Enseignement & Prière',
      headquarters: 'Siège: Total Nsimeyong, Yaoundé, Cameroun',
      everyoneWelcome: 'Tout le monde est le bienvenu! Venez comme vous êtes.',

      // Ministries
      ourMinistries: 'Nos Ministères',
      findYourPlace: 'Trouvez votre place pour servir et grandir',
      joinAMinistry: 'Rejoindre un Ministère',
      worshipTeamName: 'Équipe de Louange (Lévites)',
      worshipTeamDesc: 'Introduire la présence de Dieu à travers la musique prophétique et le culte dirigé par l\'Esprit',
      youthForImpactName: 'Jeunesse pour l\'Impact',
      youthForImpactDesc: 'Donner du pouvoir à la prochaine génération à travers le mentorat, le service et le réveil',
      mothersOfNationsName: 'Mères des Nations',
      mothersOfNationsDesc: 'Un réseau de soutien et de prière pour les femmes marchant dans leur but donné par Dieu',
      intercessionArmyName: 'Armée d\'Intercession',
      intercessionArmyDesc: 'Guerriers se tenant dans la brèche pour l\'église et les nations',
      evangelismSquadName: 'Escouade d\'Évangélisation',
      evangelismSquadDesc: 'Porter l\'Évangile dans les rues, les hôpitaux, les prisons et les communautés reculées',
      childrenMinistryName: 'Ministère des Enfants',
      childrenMinistryDesc: 'Nourrir les jeunes cœurs pour connaître et aimer Jésus dès le jeune âge',

      // Forms
      formsAndRegistration: 'Formulaires et Inscription',
      connectThroughForms: 'Connectez-vous avec nous via ces formulaires',
      shareYourTestimony: 'Partagez Votre Témoignage',
      newConvertForm: 'Formulaire de Nouveau Converti',
      membershipForm: 'Formulaire d\'Adhésion',
      registerForIFCMEducationalProgram: 'S\'inscrire au Programme Éducatif IFC',
      counselingAppointment: 'Rendez-vous de Conseil',
      joinAServiceGroup: 'Rejoindre un Groupe de Service',
      preMaritalCounseling: 'Conseil Pré-Marital',
      postMaritalCounseling: 'Conseil Post-Marital',
      childDedication: 'Dédicace d\'Enfant',
      invitedGuestForm: 'Formulaire d\'Invité',
      myAnsweredPrayerSlip: 'Mon Prière Répondue',

      // Form placeholders
      fullName: 'Nom Complet *',
      emailAddress: 'Adresse Email *',
      phoneNumber: 'Numéro de Téléphone',
      yourTestimony: 'Votre Témoignage *',
      dateOfTestimony: 'Date du Témoignage',
      dateOfConversion: 'Date de Conversion *',
      howDidYouHear: 'Comment avez-vous entendu parler de IFC ?',
      prayerRequests: 'Demandes de Prière',
      address: 'Adresse *',
      dateOfBirth: 'Date de Naissance *',
      maritalStatus: 'État Civil',
      occupation: 'Profession',
      emergencyContactName: 'Nom du Contact d\'Urgence',
      emergencyContactPhone: 'Téléphone du Contact d\'Urgence',
      programOfInterest: 'Programme d\'Intérêt *',
      previousMinistryExperience: 'Expérience Ministérielle Précédente',
      whatDoYouHopeToGain: 'Que espérez-vous gagner ?',
      preferredDate: 'Date Préférée *',
      preferredTime: 'Heure Préférée',
      typeOfCounseling: 'Type de Conseil',
      briefDescriptionOfIssue: 'Brève description du problème *',
      serviceGroup: 'Groupe de Service *',
      relevantExperienceOrSkills: 'Expérience ou Compétences Pertinentes',
      availability: 'Disponibilité (jours/heures)',
      partner1FullName: 'Nom Complet Partenaire 1 *',
      partner1Email: 'Email Partenaire 1 *',
      partner1Phone: 'Téléphone Partenaire 1 *',
      partner2FullName: 'Nom Complet Partenaire 2 *',
      partner2Email: 'Email Partenaire 2 *',
      partner2Phone: 'Téléphone Partenaire 2 *',
      expectedWeddingDate: 'Date de Mariage Prévue',
      howLongHaveYouBeenDating: 'Depuis combien de temps sortez-vous ensemble ?',
      anySpecificConcerns: 'Préoccupations spécifiques ou sujets à discuter ?',
      spouseName: 'Nom du Conjoint',
      yearsMarried: 'Années de Mariage',
      issuesToAddress: 'Problèmes que vous souhaitez aborder *',
      parent1FullName: 'Nom Complet Parent 1 *',
      parent1Email: 'Email Parent 1 *',
      parent1Phone: 'Téléphone Parent 1 *',
      parent2FullName: 'Nom Complet Parent 2',
      parent2Email: 'Email Parent 2',
      parent2Phone: 'Téléphone Parent 2',
      childFullName: 'Nom Complet de l\'Enfant *',
      childDateOfBirth: 'Date de Naissance de l\'Enfant *',
      eventServiceAttending: 'Événement/Service Assisté *',
      numberOfGuests: 'Nombre d\'Invités (vous inclus)',
      specialNeeds: 'Besoins Spéciaux ou Accommodations',
      originalPrayerRequest: 'Demande de Prière Originale *',
      howGodAnswered: 'Comment Dieu a Répondu *',
      dateAnswered: 'Date Répondue',
      additionalInformation: 'Informations Supplémentaires',
      submitForm: 'Soumettre le Formulaire',

      // Leadership
      prophetName: 'Prophète W.T. Milton',
      prophetDescription: 'Le Prophète W.T. Milton est un serviteur de Dieu expérimenté avec un manteau prophétique et une profonde passion pour le disciple. Appelé au ministère par une rencontre divine, il a consacré sa vie à élever des guerriers de la fin des temps enracinés dans le Christ. Sous sa direction, l\'IFCM a grandi à la fois spirituellement et numériquement, impactant des vies à travers le Cameroun et au-delà.',
      leader1Name: 'Pasteur Anna N.',
      leader2Name: 'Évangéliste Samuel T.',
      leader3Name: 'Sœur Martha L.',
      leader4Name: 'Frère Joel M.',

      // Events
      upcomingEvents: 'Événements à Venir',
      joinUsForLifeChangingExperiences: 'Rejoignez-nous pour des expériences qui changent la vie',

      // Give
      partnerWithUs: 'Partenaire Avec Nous',
      supportTheKingdomWork: 'Soutenez le travail du Royaume par vos dons',
      mobileMoney: 'Argent Mobile',
      mtnMoMo: 'MTN MoMo',
      ifcProjects: 'Projets IFC',
      orangeMoney: 'Orange Money',
      tithesOfferings: 'Dîmes et Offrandes',
      waysToGive: 'Façons de Donner',
      tithesOfferingsDesc: 'Soutenir les opérations régulières de l\'église',
      kingdomCenterProject: 'Projet Centre du Royaume',
      buildOurPermanentWorshipCenter: 'Construire notre centre de culte permanent',
      mercyHandsProject: 'Projet Mains de Miséricorde',
      supportHumanitarianOutreach: 'Soutenir l\'aide humanitaire',
      missionsEvangelism: 'Missions et Évangélisation',
      reachTheUnreached: 'Atteindre les non-atteints avec l\'Évangile',
      giveQuote: '"Donnez, et il vous sera donné. Une bonne mesure, tassée, secouée et débordante." - Luc 6:38',

      // Contact
      contactUs: 'Contactez-Nous',
      wedLoveToHearFromYou: 'Nous aimerions avoir de vos nouvelles',
      locationLabel: 'Emplacement',
      phoneLabel: 'Téléphone',
      emailLabel: 'Email',
      followUs: 'Suivez-Nous',
      sendUsAMessage: 'Envoyez-Nous un Message',
      yourName: 'Votre Nom *',
      yourEmail: 'Votre Email *',
      yourPhone: 'Votre Téléphone',
      yourMessage: 'Votre Message *',
      sendMessage: 'Envoyer le Message',

      // Beliefs
      belief1Title: 'Aimez-vous les uns les autres:',
      belief1Content: '(Matthieu 5:43-44) Jésus a dit que la seule façon dont le monde saurait que vous êtes mes disciples est quand vous obéissez à mon commandement qui est, aimez-vous les uns les autres (Jean 13:34-35). La forme la plus élevée de Spiritualité se manifeste à travers l\'AMOUR. (1Jean 2:9, 12, Rom 13:8, 1Jean 4:7-8, 16, 20-21)',
      belief2Title: 'La Sainte Bible:',
      belief2Content: 'À l\'Augmentation de la Foi du Christ Ministère, nous croyons que la parole de Dieu est notre vérité évangélique et tout ce dont nous avons besoin pour notre monde mourant parce que c\'est la puissance de Dieu pour le salut. (Romains 1:16, Matthieu 4; 4, Actes 6:4, Matt 8:8)',
      belief3Title: 'L\'Usage du Nom de Jésus',
      belief3Content: 'À I.F.C.M, nous faisons toutes les demandes et pétitions au nom de Jésus (Phil 2:9-11, Jean 14; 13-14, 1Jean 3:22-23).',
      belief4Title: 'La Divinité (Trinité):',
      belief4Content: 'Cela parle de l\'union de Dieu le Père, le Fils et le Saint-Esprit. (Col 2:9). Ils rendent témoignage au ciel (unis) (1Jean 5:7, Matt 28:19, Genèse 1:26-27, Jean 1:14, Actes 3: 4)',
      belief5Title: 'Baptême d\'eau:',
      belief5Content: 'Le mot baptême vient d\'un mot grec \'baptizo\' qui signifie: Immerger, Submerger ou enterrer. L\'immersion c\'est-à-dire (plonger les croyants dans l\'eau) montre leur mort, enterrement et résurrection avec Christ Jésus. En d\'autres termes, le baptême est un sacrement commandé à nous par Christ Jésus qui signifie notre mort et résurrection avec Lui à travers notre foi dans la puissance active de Dieu qui a ressuscité Christ de la mort. (Col 2;13, Matt 29:19, Marc 16:13-16, Marc 1:9).',
      belief6Title: 'Baptême du Saint-Esprit:',
      belief6Content: 'Le baptême du Saint-Esprit est l\'investissement par le Saint-Esprit pour un signe et pour nous porter témoignage (Actes 1:4-5, 8, marc 1:8). La capacité de parler en langues suit (Actes 2:4, 1 Cor 14:2, 4, 14)',
      belief7Title: 'Puissance et Autorité:',
      belief7Content: 'Nous croyons que toute Autorité est en Jésus et Il nous a donné cette autorité pour fournir des solutions aux problèmes des gens en Son nom.',
      belief8Title: 'L\'importance de la Croix:',
      belief8Content: 'Comment Jésus est mort et ressuscité, et son sang a payé le prix pour notre salut. Nous savons que par ses plaies nous avons été guéris',
      belief9Title: 'Repentance:',
      belief9Content: 'La repentance signifie se détourner de ses mauvaises voies, conversion de ceux qui sont dans le monde et aussi ceux qui étaient autrefois dans la foi et ont fait marche arrière (Matt 4:16-17, Actes 2:38) Actes 3:19 dit \'Repentez-vous et soyez convertis\'. Être né de nouveau est obéir (Rom 10:9-10), être né de Dieu (Jean 1:13, 1Pierre 1:23).',
      belief10Title: 'Jeûne et Prières:',
      belief10Content: 'Les chrétiens sont liés à jeûner et prier, qui est l\'un des moyens sûrs par lesquels nous nous approchons de Dieu (Matt 9:15). Nous recevons de Dieu à travers les prières (Marc 11:24, Luc 2:37, Jacques 5:16, Matt 4:2, Matt 17: 21).',
      belief11Title: 'Miracles et Guérisons, (Dons de Dieu, Imposition des Mains):',
      belief11Content: 'Dieu agit de diverses manières, les miracles que nous voyons sont par la puissance de Dieu. Imaginez un boiteux marchant, l\'aveugle voyant etc c\'est donné par Dieu (1 Cor 12:10, Actes 15:12, Gal 5:3). La guérison est de Dieu pas de l\'homme (1Corin 12:9) Jésus lui-même a donné la proclamation en Marc 16:18 \'Ils prendront des serpents et s\'ils boivent une eau mortelle, elle ne leur nuira pas, ils imposeront les mains sur les malades et ils recouvreront\'. Jacques 5:14-16, Marc 6:13, 1 Timothée 5:22, parle aussi d\'onction avec l\'huile d\'olive pour la guérison.',
      belief12Title: 'Discipleship:',
      belief12Content: 'L\'acte de faire continuer le christianisme est de suivre. Il doit y avoir un maître (Luc 14:26-27) Jésus est le maître invisible mais il met un maître en place que nous pouvons voir (surveillant du ministère), (Mat 9:14). L\'apôtre Paul était un maître en 1Corin 4:15 et 1 Cor 11:1 il a dit \'suivez-moi comme je suis Christ\'.',
      belief13Title: 'Soumission à l\'Autorité de l\'Église.',
      belief13Content: 'La loyauté de chaque membre devrait être primordiale. Il ne devrait jamais y avoir de place pour les groupes qui résistent à l\'autorité (fractions pour résister à l\'autorité), (Héb 13:17, Mat 10:24), (voir Vérité Essentielle pour les Débutants en Foi Chrétienne et lire sur Loyauté par W.T Milton).',
      belief14Title: 'Pardon et Réconciliation',
      belief14Content: 'La constitution de la justification est le pardon, qui est pardonner ou être pardonné. Dieu nous a absorbés de nos péchés, qui est l\'une des conditions pour devenir partie du royaume de Dieu. La Prière du Seigneur l\'explique en Matt 6:12, 15, vous devez pardonner aux autres pour que Dieu vous pardonne et si vous ne pardonnez pas, Dieu ne pardonnera pas. Voir ce que Christ a dit en Matt 18:21-22.',
      belief15Title: 'Sainte Communion (La Cène du Seigneur).',
      belief15Content: 'Jésus et ses disciples ont rompu le pain et mangé, Il a versé du vin et ils ont bu, Jésus a dit, le pain est Son corps et le vin est Son sang (1Cor 11:20, 10:16). C\'est une bénédiction du Seigneur que nous faisons en commémoration de Jésus (Matt 26:26-29, Marc 14:22-25, Luc 22:19-20). C\'est la seule chose que Christ a dit que nous devrions faire en souvenir de Lui.',
      belief16Title: 'Saint Mariage',
      belief16Content: 'Chaque homme doit être un mari à une épouse (Gen 2:24-25, Tite 1:6). Le divorce n\'est pas permis sauf à la condition d\'adultère. (Matt 5:31-32). Si vous quittez votre conjoint restez célibataire (Matt 19:9-12, 1Cor 7:10-11). Aucun croyant n\'est autorisé à épouser un incroyant (2Cor 7:16-17).',
      belief17Title: 'Intégrité',
      belief17Content: 'L\'intégrité est notre position et mot d\'ordre (Prov 20:7). Elle apporte un meilleur monde. Si toutes les familles ont l\'intégrité, leurs enfants prendront après eux et cela apportera une meilleure communauté, quartier, maison, ville, état, et monde.',
      readMoreBeliefs: 'Lire Plus →',
    }
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t, translations }}>
      {children}
    </LanguageContext.Provider>
  );
});

export default LanguageProvider;
